#!/usr/bin/env bash
./vendor/bin/phpdoc  -d src -t docs/ --template="xml" --title="Freshdesk PHP SDK (API v2) Documentation"
./vendor/bin/phpdocmd docs/structure.xml docs
rm -rf ./docs/phpdoc-cache-*
git add .
git commit -m "updated documentation"
